swagger: "2.0"
info:
  version: "0.0.1"
  title: Dog Fight App
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
schemes:  
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /hello:
    # binds a127 app logic to a route
    x-swagger-router-controller: hello_world
    get:
      description: Health check
      # used as the method name of the controller
      operationId: hello      
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            type: string
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /dogs:
    x-swagger-router-controller: dog
    get:
      description: List all dogs
      operationId: getDogs
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Dogs"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /dog:
    x-swagger-router-controller: dog
    post:
      description: Add a dog to the fight
      operationId: addDog
      parameters:
        - name: dog
          in: body
          description: dog information
          required: true
          schema:
            $ref: "#/definitions/Dog"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GeneralResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /dog/{name}:
    x-swagger-router-controller: dog
    parameters:
      - name: name
        in: path
        description: Name of dog
        required: true
        type: string
    get:
      description: Returns dog details
      operationId: getDog
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Dog"      
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    delete:
      description: Remove a dog
      operationId: removeDog
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GeneralResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /dog/{name}/fight_moves:
    x-swagger-router-controller: dog
    parameters:
      - name: name
        in: path
        description: The name of the dog to remove
        required: true
        type: string
    get:
      description: Gets dogs's fight moves
      operationId: getFightMoves
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/DogFightMoves"      
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    post:
      description: Adds a fight move for the dog
      operationId: addFightMove
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GeneralResponse"      
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /dog/{name}/distractions:
    x-swagger-router-controller: dog
    parameters:
      - name: name
        in: path
        description: The name of the dog to remove
        required: true
        type: string
    get:
      description: Gets dogs's distractions
      operationId: getDistractions
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/DogDistractions"      
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    post:
      description: Adds a distraction for the dog
      operationId: addDistraction
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GeneralResponse"      
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /dog/{name}/actions:
    x-swagger-router-controller: dog
    parameters:
      - name: name
        in: path
        description: The name of the dog to remove
        required: true
        type: string
    get:
      description: Gets dogs's actions
      operationId: getActions
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/DogActions"      
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    post:
      description: Adds an action for the dog
      operationId: addAction
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GeneralResponse"      
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /fight:
    x-swagger-router-controller: fight
    post:
      description: Start a dog fight
      operationId: start
      parameters:
        - name: dogs
          in: body
          description: Add 2 dogs to a fight
          required: true
          schema:
            $ref: "#/definitions/DogFight"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GeneralResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /listen:
    x-swagger-router-controller: listen
    post:
      description: Listens for commands
      operationId: listen
      parameters:
        - name: info
          in: body
          description: The command to listen for
          required: true
          schema:
            $ref: "#/definitions/ListenRequest"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GeneralResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"

  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  DogActions:
    type: array
    items:
      type: object
      properties:
        action:
          type: string
        value:
          type: integer
          format: int32
  DogDistractions:
    type: array
    items: 
      type: object
      properties:
        distraction:
          type: string
        value:
          type: integer
          format: int32
  DogFightMoves:
    type: array
    items:
      type: object
      properties:
        verb:
          type: string
        noun:
          type: string
        value:
          type: integer
          format: int32
  ListenRequest:
    type: object
    properties:
      token:
        type: string
        description: Slack token
      team_id:
        type: string
        description: Slack team ID
      team_domain:
        type: string
      channel_id:
        type: string
        description: Slack channel ID
      channel_name:
        type: string
        description: Slack channel name
      user_id:
        type: string
        description: User that sent the message
      user_name:
        type: string
        description: Slack user name that sent the request
      text:
        type: string
        description: The command that was sent
      trigger_word:
        type: string
        description: The trigger word        
  DogFight:
    type: array
    items:
      type: string
  Dogs:
    type: array
    items:
      type: string
  GeneralResponse:
    type: object
    properties:
      success:
        type: number
        description: returns 1 if successful
      description:
        type: string
        description: a short comment 
    required:
      - success
      - description
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
  Dog:
    required:
      - name
      - weight
    properties:
      name:
        type: string
      gender:
        type: string
      weight:
        type: integer
        format: int32
      fight_moves:
        $ref: "#/definitions/DogFightMoves"
      distractions:
        $ref: "#/definitions/DogDistractions"
      actions:
        $ref: "#/definitions/DogActions"
      
            
            
      
      
